@id=7e211575-65cc-47f2-93ba-359f98a7b2a1

PUT http://localhost:5087/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Ve",
    "description": "Vegan everything! Join us for a healthy breakfast..22",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}