@id=55c16ad7-b715-4e5f-95c6-a6f39b84c5ec

PUT http://localhost:5161/expenses/{{id}}
Content-Type: application/json

{
    "description": "Alexela",
    "category": "Transport",
    "amount": 50,
    "date": "2022-04-06T12:00:00"
}