@id=91c27cfe-3b9b-4ca8-9e71-25f93f1ab699

PUT http://localhost:5233/expenses/{{id}}
Content-Type: application/json

{
    "description": "Alexela",
    "category": "Transport",
    "amount": 50,
    "date": "2022-04-06T12:00:00"
}